
name: Executar em cada push e a cada hora


on:
  push:
  schedule:
    - cron: '0 * * * *' 

jobs:
  exemplo-job:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Rodar script personalizado 
      run: |
            echo "Workflow funcionando por push ou agendado!"
            date

